#!/bin/bash

echo "🎨 Nishuuu Themes - All Available Accent Colors"
echo "=============================================="
echo ""

echo "Available Accent Colors:"
echo "- $(printf '%-15s' 'Acid Lime') #C6FF00 - Electric lime green"
echo "- $(printf '%-15s' 'Blue') #5393FF - Classic blue accent"
echo "- $(printf '%-15s' 'Bright Teal') #57D7FF - Bright cyan-teal"
echo "- $(printf '%-15s' 'Carbon') #737374 - Elegant gray accent"
echo "- $(printf '%-15s' 'Cyan') #64FFDA - Pure cyan blue"
echo "- $(printf '%-15s' 'Deepforest') #a3c679 - Natural green accent"
echo "- $(printf '%-15s' 'Graphene') #6a90d0 - Clean blue accent"
echo "- $(printf '%-15s' 'Indigo') #758AFF - Deep indigo blue"
echo "- $(printf '%-15s' 'Lime') #80CBC4 - Fresh lime green"
echo "- $(printf '%-15s' 'Ocean') #6ebad7 - Deep blue accent"
echo "- $(printf '%-15s' 'Orange') #FF7042 - Bright orange accent"
echo "- $(printf '%-15s' 'Palenight') #a178c4 - Purple accent"
echo "- $(printf '%-15s' 'Pink') #FF669E - Vibrant pink accent"
echo "- $(printf '%-15s' 'Purple') #B54DFF - Rich purple accent"
echo "- $(printf '%-15s' 'Teal') #80CBC4 - Vibrant teal accent (default)"
echo "- $(printf '%-15s' 'Tomato') #F95044 - Vibrant tomato red"
echo "- $(printf '%-15s' 'Vira') #E9A581 - Original Vira accent"
echo "- $(printf '%-15s' 'White') #FFFFFF - Clean white accent"
echo "- $(printf '%-15s' 'Yellow') #FFCF3D - Golden yellow accent"
echo ""

echo "🚀 How to Use:"
echo "1. Look for the $(printf '\033[96m$(paintcan) Accent\033[0m') button in your status bar"
echo "2. Click it to open the accent color picker"
echo "3. Select any color from the dropdown"
echo "4. Icon theme will automatically update to match"
echo "5. Or use Command Palette: 'Nishuuu Themes: Select Accent Color'"
echo ""

echo "✅ Features:"
echo "- No hex codes in dropdown (clean interface)"
echo "- Color icons for visual selection"
echo "- Automatic icon theme synchronization"
echo "- Custom hex color support"
echo "- Only UI elements change (no syntax highlighting affected)"
echo ""

echo "🎯 What Changes with Accent Color:"
echo "- Activity bar borders and badges"
echo "- Status bar remote indicators"
echo "- Tab borders/backgrounds"
echo "- Editor cursor and find highlights"
echo "- Button and link colors"
echo "- List selections and highlights"
echo "- Panel borders and titles"
echo "- File/folder icon accents"
echo ""

echo "Done! Enjoy your new accent colors! 🎨"
