name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install VSCE
      run: npm install -g @vscode/vsce
      
    - name: Lint package.json
      run: |
        if ! jq empty package.json; then
          echo "package.json is not valid JSON"
          exit 1
        fi
        
    - name: Validate theme files
      run: |
        for theme in themes/*.json; do
          if ! jq empty "$theme"; then
            echo "$theme is not valid JSON"
            exit 1
          fi
        done
        
    - name: Package Extension
      run: vsce package
      
    - name: Check package contents
      run: |
        unzip -l *.vsix
        
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension-package
        path: '*.vsix'
